### ISSUE TITLE
Time tracking hook fails after setting the totalactivetime manually

### ISSUE THREAD

**Issue by MikeYPK** [kostajh/taskwarrior-time-tracking-hook#16]
There are times when I want to update totalactivetime outside of start and stop (e.g. if I couldn't access my machine to start ... or if I forgot to stop the task and need to fix the time later)

task modify allows me to change totalactivetime, but it stores the data in ISO-8601, which causes the hook script to fail.

I created a small patch that seems to fix the issue. Hope this helps!

[patch.txt](https://github.com/kostajh/taskwarrior-time-tracking-hook/files/931690/patch.txt)

**Comment by alexhunsley** [comment]
I've opened a pull request containing @MikeYPK's fix: 
https://github.com/kostajh/taskwarrior-time-tracking-hook/pull/18
