### ISSUE TITLE
Use duration UDA type

### ISSUE THREAD

**Issue by kostajh** [kostajh/taskwarrior-time-tracking-hook#2]
As far as I can tell, the new `calc` command isn't supported in reports. So while I can look at my task report and see that I have 3654 seconds in a task, I'd rather see that I have 1.015 hours logged.

Duration UDAs store seconds in the field value, but take values like "1.015hours" or "32minutes" as arguments. If you do `task export` on a field using the duration type, you'll see the seconds values, but in the reports you get a human readable value.

**Comment by astr0gator** [comment]
`task -r mine` gives me this format of duration: PT20M55S
`taskwarrior-tui -r mine` gives me this format of duration: 1255 seconds

Is there a way how I can see 0:20:55 (or ideally 0:21) in taskwarrior-tui?
