### ISSUE TITLE
Seeing a diagnostic message each time (No handlers could be found for logger "taskw.taskrc")

### ISSUE THREAD

**Issue by arooni** [kostajh/taskwarrior-time-tracking-hook#20]
```
[I]  ✘  ~/.t/hooks  task stop 120
No handlers could be found for logger "taskw.taskrc"
Total Time Tracked: 0:04:01.141180 (0:00:17.141180 in this instance)
```

The taskw.taskrc thing... I looked thru the   /usr/local/lib/python2.7/dist-packages/taskwarrior_time_tracking_hook/__init__.py
 ;; file but didn't see any reference to it

anyways thanks for something thats very useful

**Comment by kostajh** [comment]
@arooni I'm not sure this is an issue specific to this project. Could you file an issue at https://github.com/ralphbean/taskw please?
