### ISSUE TITLE
Pip installs older version that doesn't work

### ISSUE THREAD

**Issue by nielsene54** [kostajh/taskwarrior-time-tracking-hook#7]
When using pip, I noticed that it was installing version 0.1.2 of the time tracking hook, which I was never able to get working. The problem was that whenever you would use the start command it would just run on an endless loop and nothing would ever happen until you terminated it yourself. I am using Taskwarrior 2.4.0.beta3.

**Comment by kostajh** [comment]
Could you clone the repo and try `pip install -e /path/to/repo --user` and let me know if that works for you?

**Comment by kostajh** [comment]
Also, @nielsene54, @raz- or @coddingtonbear if any of you all are interested in taking ownership/maintenance of this repo please let me know.

**Comment by nielsene54** [comment]
@kostajh On that ownership/maintenance note, I just want you to know that I recently built a slightly more robust time tracking hook for Taskwarrior during my employers innovation sprint. I borrowed some things from this repo in doing so, but I am not entirely sure when it will be available to the public as they do not yet have a public repo and things like that need to happen. I am going to get this set up next time we do an innovation sprint (in 2 or 3 months I believe), and I am definitely going to at least put a thank you to this repo. If you want to pass the buck at that time it is up to you but I would be fine with that, as what my hook does is pretty much the same as yours with a few additional features.

**Comment by raz-** [comment]
@kostajh Thanks, this works for me.

**Comment by coddingtonbear** [comment]
Oh, I can help you out, @kostajh, if all it is is merging PRs and pushing up releases; just add me at a collaborator on this repo... if I'm not already.

**Comment by coddingtonbear** [comment]
Just pushed up a new version to PyPI -- https://pypi.python.org/pypi?:action=display&name=taskwarrior-time-tracking-hook&version=0.1.4 .

PyPI installs should now properly install the latest version.

Cheers!

**Comment by kostajh** [comment]
thanks @coddingtonbear!
